cloud:
  aws:
    credentials:
      access-key: AKIAU4WWLRGNBPUBUW3Y
      secret-key: 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
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: redeyesncodedev


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090